sudo: false

language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - coverage run manage.py test && coverage report

after_success:
  - codecov
